
@extends('layouts.adminlayout')
@section('title',"Terms & Conditions | MedCab")
@section('description',"Discover MedCab's user-friendly Terms and Conditions for its customers, drivers and partners. Get crystal-clear guidelines for a smooth experience.")
@section('keywords',"MedCab Terms and Conditions, MedCab T&C, MedCab Terms & Conditions, MedCab App Terms and Conditions")
@section('main')

<style>
    .text-section >ul>li{
        list-style: disc;
    }
</style>
<!-- Term and Condition section  start-->
    <section class="header-top-margin py-5">
        <div class="container">
            <h1 class="title-text text-center mb-2">
            Terms and Conditions
            </h1>
            <div class="text-section">
                <p class="p-text text-center">
                Please read these terms and conditions carefully before using Our Service.<br/>
                <br/>
                </p>
                <p class="p-heading">Interpretation and Definitions</p>
                <p class="p-text">
                <b>Interpretation</b><br/>
                The words of which the initial letter is capitalized have meanings defined under the following conditions.
                The following definitions shall have the same meaning regardless of whether they appear in singular or in
                plural.<br/><br/>
                <b>Definitions</b><br/>
                For the purposes of these Terms and Conditions:<br/>
                <ul>
                    <li>“Application” means the software program provided by the Company downloaded by You on any
                        electronic device, named Medcab Partner/Medcab Driver/Medcab Customer.
                    </li>
                    <li>
                        “Application Store” means the digital distribution service operated and developed by Apple Inc.
                        (Apple App Store) or Google Inc. (Google Play Store) in which the Application has been
                        downloaded.
                    </li>
                    <li>
                        “Affiliate” means an entity that controls, is controlled by or is under common control with a party,
                        where "control" means ownership of 50% or more of the shares, equity interest or other securities
                        entitled to vote for election of directors or other managing authority.
                    </li>
                    <li>“Account” means a unique account created for You to access our Service or parts of our Service.</li>
                    <li>
                        MedCab (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to
                        MedCab Care Pvt. Ltd., Uttar Pradesh(Healthcare Service Provider).
                    </li>
                    <li>“Country” refers to Lucknow.</li>
                    <li>“Content” refers to content such as text, images, or other information that can be posted, uploaded,
                        linked to or otherwise made available by You, regardless of the form of that content.</li>
                    <li>
                        “Device” means any device that can access the Service such as a computer, a cell phone or a
                        digital tablet.
                    </li>
                    <li>
                        “Feedback” means feedback, innovations or suggestions sent by You regarding the attributes,
                        performance or features of our Service.</li>
                    <li>“Service” refers to the Website.</li>
                    <li>“Terms and Conditions” (also referred as "Terms") mean these Terms and Conditions that form the
                        entire agreement between You and the Company regarding the use of the Service. This Terms and
                        Conditions Agreement was generated by TermsFeed Mobile App Terms and Conditions Generator.
                        Third-party Social Media Service” means any services or content (including data, information,
                        products or services) provided by a third-party that may be displayed, included or made available by
                        the Service.
                    </li>
                    <li>“Website” refers to MedCab, accessible from medcab.in .</li>
                    <li>“You” means the individual accessing or using the Service, or the company, or other legal entity on
                        behalf of which such individual is accessing or using the Service, as applicable.</li>
                </ul>
                <br/>
                <b class="p-heading">Acknowledgment</b>
                These are the Terms and Conditions governing the use of this Service and the agreement that operates
                between You and the Company. These Terms and Conditions set out the rights and obligations of all users
                regarding the use of the Service.<br/>
                Your access to and use of the Service is conditioned on Your acceptance of and compliance with these
                Terms and Conditions. These Terms and Conditions apply to all visitors, users and others who access or
                use the Service.<br/>
                By accessing or using the Service You agree to be bound by these Terms and Conditions. If You disagree
                with any part of these Terms and Conditions then You may not access the Service.<br/>
                You represent that you are over the age of 18. The Company does not permit those under 13 to use the
                Service.<br/>
                Your access to and use of the Service is also conditioned on Your acceptance of and compliance with the
                Privacy Policy of the Company. Our Privacy Policy describes Our policies and procedures on the collection,
                use and disclosure of Your personal information when You use the Application or the Website and tells You
                about Your privacy rights and how the law protects You. Please read Our Privacy Policy carefully before
                using Our Service.<br/><br/>
                <b class="p-heading">User Accounts</b>
                When You create an account with Us, You must provide Us information that is accurate, complete, and
                current at all times. Failure to do so constitutes a breach of the Terms, which may result in immediate
                termination of Your account on Our Service.<br/>
                You are responsible for safeguarding the password that You use to access the Service and for any activities
                or actions under Your password, whether Your password is with Our Service or a Third-Party Social Media
                Service.<br/>
                You agree not to disclose Your password to any third party. You must notify Us immediately upon becoming
                aware of any breach of security or unauthorized use of Your account.<br/>
                You may not use as a username the name of another person or entity or that is not lawfully available for
                use, a name or trademark that is subject to any rights of another person or entity other than You without
                appropriate authorization, or a name that is otherwise offensive, vulgar or obscene
                By accessing or using the Service you agree to be bound by these Terms. If you disagree
                with any part of the terms then you may not access the Service.<br/><br/>
                <b class="p-heading">Purchases</b>
                If you wish to purchase any product or service made available through the Service ("Purchase"),
                you may be asked to supply certain information relevant to your Purchase including, without
                limitation, your …
                The Purchases section is for businesses that sell online (physical or digital). For the full
                disclosure section, create your own Terms and Conditions.<br/><br/>
                <span class="p-heading">Subscriptions</span>
                Some parts of the Service are billed on a subscription basis ("Subscription(s)"). You will be billed in
                advance on a recurring ...<br/>
                The Subscriptions section is for SaaS businesses. For the full disclosure section, create your
                own Terms and Conditions.<br/><br/>
                <span class="p-heading">Content</span>
                Our Service allows you to post, link, store, share and otherwise make available certain information,
                text, graphics, videos, or other material ("Content"). You are responsible for the …
                The Content section is for businesses that allow users to create, edit, share, make content on
                their websites or apps. For the full disclosure section, create your own Terms and Conditions.
                <br/><br/>
                <span class="p-heading">Governing Law</span>
                The laws of the Country, excluding its conflicts of law rules, shall govern this Terms and Your use of the
                Service. Your use of the Application may also be subject to other local, state, national, or international laws.
                <br/><br/>
                <span class="p-heading"> Disputes Resolution</span>
                If You have any concern or dispute about the Service, You agree to first try to resolve the dispute informally
                by contacting the Company
                <br/><br/>
                <span class="p-heading">Limitation of Liability</span>
                Notwithstanding any damages that You might incur, the entire liability of the Company and any of its
                suppliers under any provision of this Terms and Your exclusive remedy for all of the foregoing shall be
                limited to the amount actually paid by You through the Service or 100 USD if You haven't purchased
                anything through the Service.<br/>
                To the maximum extent permitted by applicable law, in no event shall the Company or its suppliers be liable
                for any special, incidental, indirect, or consequential damages whatsoever (including, but not limited to,
                damages for loss of profits, loss of data or other information, for business interruption, for personal injury,
                loss of privacy arising out of or in any way related to the use of or inability to use the Service, third-party
                software and/or third-party hardware used with the Service, or otherwise in connection with any provision of
                this Terms), even if the Company or any supplier has been advised of the possibility of such damages and
                even if the remedy fails of its essential purpose.<br/>
                Some states do not allow the exclusion of implied warranties or limitation of liability for incidental or
                consequential damages, which means that some of the above limitations may not apply. In these states,
                each party's liability will be limited to the greatest extent permitted by law.
                <br/><br/>

                <span class="p-heading">Links To Other Web Sites</span>
                Our Service may contain links to third-party web sites or services that are not owned or controlled
                by MEdCab.
                MedCab has no control over, and assumes no responsibility for, the content,
                privacy policies, or practices of any third party web sites or services. You further acknowledge and
                agree that MedCab shall not be responsible or liable, directly or indirectly, for any
                damage or loss caused or alleged to be caused by or in connection with use of or reliance on any
                such content, goods or services available on or through any such web sites or services.
                <br/><br/>
                <span class="p-heading">Changes</span>
                We reserve the right, at our sole discretion, to modify or replace these Terms at any time. If a
                revision is material we will try to provide at least 30 (change this) days' notice prior to any new terms
                taking effect. What constitutes a material change will be determined at our sole discretion.
                <br/><br/>
                <span class="p-heading">Contact Us</span>
                If you have any questions about these Terms, please contact us.
                </p><br/>
                <span class="text-center my-3 d-block">Our Terms and Conditions were last updated on 22 May 2023.</span>
            </div>
        </div>
    </section>
<!-- Term and Condition section End -->
@endsection
